# Generated by Django 5.1.3 on 2024-12-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='administrator', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='dev', max_length=20),
            preserve_default=False,
        ),
    ]
