# Generated by Django 5.1.3 on 2024-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_sku_inventory_sku_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warehouse_number',
            field=models.CharField(),
        ),
    ]
