# Generated by Django 5.1.3 on 2024-12-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_warehouse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
