# Generated by Django 5.1.3 on 2024-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
