# Generated by Django 5.1.3 on 2024-12-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='location',
            new_name='inventory_id',
        ),
    ]
