# Generated by Django 5.1.3 on 2024-12-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0002_alter_part_crate_size_alter_part_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('estimated_duration', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('due_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('order_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('status', models.BooleanField(null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
