# Generated by Django 5.1.3 on 2024-12-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderpart_sku_color'),
        ('parts', '0007_part_sku_color_alter_part_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpart',
            name='sku',
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='sku_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
    ]
