# Generated by Django 5.1.3 on 2024-12-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderpart_sku_alter_orderpart_sku_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='qty',
            field=models.FloatField(),
        ),
    ]
