# Generated by Django 5.1.3 on 2024-12-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('sku', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('old_sku', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sku_color', models.CharField(max_length=255)),
                ('old_sku_color', models.CharField(max_length=255)),
                ('qty_per_box', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('lbs1400', models.IntegerField()),
                ('crate_size', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
