# Generated by Django 5.1.3 on 2024-12-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_part_old_sku_color_remove_part_sku_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
