# Generated by Django 5.1.3 on 2024-12-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_part_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='crate_size',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
