# Generated by Django 5.1.3 on 2024-12-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_part_lbs1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='sku',
            new_name='sku_color',
        ),
        migrations.AddField(
            model_name='part',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        )

    ]
