# Generated by Django 5.1.3 on 2024-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_part_sku_color_alter_part_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='sku_color',
            field=models.CharField(default='default', max_length=255, primary_key=True, serialize=False),
        ),
    ]
