# Generated by Django 5.1.3 on 2024-12-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('parts', '0002_alter_part_crate_size_alter_part_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingLists',
            fields=[
                ('manufacturing_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturigListItem',
            fields=[
                ('manufacturing_list_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('manufacturing_process', models.CharField(choices=[('cutting', 'cutting'), ('bending', 'bending'), ('painting', 'painting'), ('completed', 'completed'), ('cutting QA', 'cuttingQA'), ('bending QA', 'bendingQA'), ('painting QA', 'paintingQA')], max_length=25, null=True)),
                ('process_progress', models.CharField(choices=[('ToDo', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=25, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
                ('manufacturing_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingLists.manufacturinglists')),
            ],
        ),
    ]
