# Generated by Django 5.1.3 on 2024-12-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturingLists', '0003_rename_manufacturiglistitem_manufacturinglistitem'),
        ('parts', '0007_part_sku_color_alter_part_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturinglistitem',
            name='sku',
        ),
        migrations.AlterField(
            model_name='manufacturinglistitem',
            name='sku_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
    ]
